AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  An Amazon Kinesis Firehose stream processor that extracts individual log events from records sent by Cloudwatch Logs subscription filters.

  Last Modified: 8 Nov, 2017
  Authors:  Tarik Makota <tmak@amazon.com>, Kevin Deng <chaodeng@amazon.com>

Outputs:
  FirehoseKinesisInlineProcessor:
    Description: "Lambda Function ARN that can be used to configure a Firehose Delivery Stream with inline processing."
    Value: !GetAtt KinesisFirehoseCloudwatchLogsProcessor.Arn

Resources:
  KinesisFirehoseCloudwatchLogsProcessor:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./amazon-kinesis-firehose-cloudwatch-logs-processor.zip
      Description: An Amazon Kinesis Firehose stream processor that converts input records from VPC Flow Logs to raw ingestable format
      MemorySize: 256
      Timeout: 60
